KAP/urls.py
from django.contrib import admin
from django.urls import path, include
from patient.views import user_login, user_logout, success
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include(('patient.urls','patient'),namespace='patient')),
    path('survey/', include(('survey.urls','survey'),namespace='survey')),
    path('appointments/',include(('appointments.urls','appointments'),namespace='appointments')),    

    path('login/', user_login, name="user_login"),
    path('success/', success, name="user_success"),
    path('logout/', user_logout, name="user_logout"),
]

survey/urls.py
from django.urls import path
from survey.views import *

urlpatterns = [
    path('', index, name='survey_list'),
    path('<int:id>/details', details, name='survey_details'),
    path('<int:id>/', question_content, name='question_content'),
    ]

survey/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class TextQuestion(models.Model):
    title = models.TextField()
    status = models.CharField(default='inactive', max_length=10)
    author = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    @property
    def choices(self):
        return self.textchoice_set.all()


class TextChoice(models.Model):
    question = models.ForeignKey('survey.TextQuestion', on_delete=models.CASCADE)
    text = models.TextField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __self__(self):
        return self.text

    @property
    def votes(self):
        return self.textanswer_set.count()


class TextAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(TextChoice, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{0} {1}".format(self.user.first_name, self.choice.text)

survey/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse
from django.contrib.auth.decorators import login_required
from survey.models import *


@login_required(login_url="/login/")
def index(request):
    context = {}
    questions = TextQuestion.objects.all()
    context['title'] = 'surveys'
    context['questions'] = questions
    return render(request, 'survey/index.html', context)


@login_required(login_url="/login/")
def details(request, id=None):
    context = {}
    try:
        question = TextQuestion.objects.get(id=id)
    except:
        raise Http404
    context['question'] = question
    return render(request, 'survey/details.html', context)


@login_required(login_url="/login/")
def question_content(request, id=None):
    if request.method == "GET":
        context = {}
        try:
            question = TextQuestion.objects.get(id=id)
        except:
            raise Http404
        context['question'] = question
        return render(request, "survey/question_content.html", context)
    if request.method == "POST":
        user_id = 1
        data = request.POST
        ret = TextAnswer.objects.create(user_id=user_id, choice_id=data['choice'])
        if ret:
            return HttpResponse("Your vote is done successfully")
        else:
            return HttpResponse("Your vote is not done successfully")

templates/survey/details.html
{% extends 'base.html' %}


{% block content %}
    <p>
        <h3>{{question.title}}</h3>
    </p>
    <div class="list-group col-md-6">
    {% for choice in question.choices %}
        <a class="list-group-item" href="{% url 'survey:question_content' question.id %}">
            <span class="badge badge-pill badge-primary float-right">{{choice.votes}}</span>
            {{choice.text}}
        </a>
        <!-- <p> ({{choice.votes}})</p> -->
        {% empty %}
        <div class="list-group-item">There is no choice available for this question.</div>
        {% endfor %}
    </div>
    <br>
    <div class="col-md-12"><b>Created by: </b> {{question.created_by.first_name}}</div>
{% endblock content %}

templates/survey/index.html
{% extends 'base.html' %}


{% block content %}
    <p>
    <h3>List of {{ title }}</h3>
    </p>

    <div class="table-responsive-sm">
        {% if questions %}
            <table class="table table-bordered">
                <thead class="thead-light">
                <tr>
                    <th>Survey</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for question in questions %}
                    <tr>
                        <th scope="row">
                            <a class="" href="{% url 'survey:question_content' question.id %}">{{ question.title }}</a>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-primary" href="{% url 'survey:survey_details' question.id %}">Details</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>There is no question available.</p>
        {% endif %}
    </div>
{% endblock content %}

templates/survey/question_content.html
{% extends 'base.html' %}


{% block content %}
    <p>
        <h3>{{question.title}}</h3>
    </p>
    <form method="POST" action="{% url 'survey:question_content' question.id %}">
        {% csrf_token %}
    {% for choice in question.choices %}
        <div class="radio">
            <label>
                <input type="radio" name="choice" value="{{choice.id}}">
                {{choice.text}}
            </label>
        </div>
    {% empty %}
        <p>There is no choice available for this question.</p>
    {% endfor %}
        <button class="btn btn-dark" type="submit" value="Vote">Vote</button>
    </form>
{% endblock content %}