KAP/urls.py
from django.contrib import admin
from django.urls import path, include
from patient.views import user_login, user_logout, success
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include(('patient.urls','patient'),namespace='patient')),
    path('survey/', include(('survey.urls','survey'),namespace='survey')),
    path('appointments/',include(('appointments.urls','appointments'),namespace='appointments')),    

    path('login/', user_login, name="user_login"),
    path('success/', success, name="user_success"),
    path('logout/', user_logout, name="user_logout"),
]

patient/urls.py
from django.urls import path
from patient.views import *

urlpatterns = [
    path('', patient_list, name='list'),
    path('<int:id>/details/', patient_details, name="details"),
    path('<int:id>/edit/', patient_edit, name="edit"),
    path('add/', patient_add, name="add"),
    path('<int:id>/delete/', patient_delete, name="delete"),
    ]

patient/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class PatientProfile(models.Model):
    id_code = models.CharField(max_length=20, null=False, blank=False)
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)

    def __str__(self):
        return "{0} {1}".format(self.user.first_name, self.user.last_name)

patient/forms.py
from django import forms
from django.contrib.auth.models import User, Group


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    role = forms.ModelChoiceField(queryset=Group.objects.all())

    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'email', 'username',
                  'password']

        label = {
            'password': 'Password'
        }

    def __init__(self, *args, **kwargs):
        if kwargs.get('instance'):
            initial = kwargs.setdefault('initial',{})
            if kwargs['instance'].groups.all():
                initial['role'] = kwargs['instance'].groups.all()(0)
            else:
                initial['role'] = None

        forms.ModelForm.__init__(self, *args, **kwargs)


    def save(self):
        password = self.cleaned_data.pop('password')
        role = self.cleaned_data.pop('role')
        u = super().save()
        u.groups.set([role])
        u.set_password(password)
        u.save()
        return u

patient/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from patient.forms import UserForm
from KAP.decorators import admin_check, doctor_check, user_check

def user_login(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            if request.GET.get('next', None):
                return HttpResponseRedirect(request.GET['next'])
            return HttpResponseRedirect(reverse('patient:list'))
        else:
            context['error'] = "Provide valid credentials"
            return render(request, "auth/login.html", context)
    else:
         return render(request, "auth/login.html", context)


@login_required(login_url="/login/")
def success(request):
    context = {}
    context['user'] = request.user
    return render(request, "auth/success.html", context)


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))


@login_required(login_url="/login/")
def patient_list(request):
    context = {}
    context['users'] = User.objects.all()
    context['title'] = 'Patients'
    return render(request, 'patient/index.html', context)


@login_required(login_url="/login/")
def patient_details(request, id=None):
    context = {}
    context['users'] = get_object_or_404(User, id=id)
    context['title'] = 'Patients'
    return render(request, 'patient/details.html', context)


@login_required(login_url="/login/")
@doctor_check
def patient_add(request):
    context = {}
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        context['user_form'] = user_form
        if user_form.is_valid():
            u = user_form.save()
            return HttpResponseRedirect(reverse('patient:list'))
        else:
            return render(request, 'patient/add.html', context)
    else:
        user_form = UserForm()
        context['user_form'] = user_form
        return render(request, 'patient/add.html', context)


@login_required(login_url="/login/")
def patient_edit(request, id=None):
    context = {}
    user = get_object_or_404(User, id=id)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('patient:list'))
        else:
            return render(request, 'patient/edit.html', context)
    else:
        user_form = UserForm(instance=user)
        context['user_form'] = user_form
        return render(request, 'patient/edit.html', context)


@login_required(login_url="/login/")
@doctor_check
def patient_delete(request, id=None):
    user = get_object_or_404(User, id=id)
    if request.method == "POST":
        user.delete()
        return HttpResponseRedirect(reverse('patient:list'))
    else:
        context = {}
        context['user'] = user
        return render(request, 'patient/delete.html', context)

templates/patient/add.html
{% extends 'base.html' %}


{% block content %}
<br>
    <form method="POST">
        {% csrf_token %}
        <table class="table table-bordered">
            {{user_form.as_table}}
        </table>
        <br>
        <button type="submit" class="btn btn-success float-right">Add Patient</button>
    </form>
{% endblock content %}

templates/patient/delete.html
{% extends 'base.html' %}


{% block content %}
<br>
    <h2>{{user.first_name}} &nbsp; {{user.last_name}}</h2>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure to delete this Patient?</p>
        <input type="submit" value="Yes">
    </form>
{% endblock content %}

templates/patient/details.html
{% extends 'base.html' %}


{% block content %}
<br>
    <table class="table table-light table-bordered table-striped">
        <tbody>
        <tr>
            <th>First Name</th>
            <td>{{user.first_name}}</td>
        </tr>
        <tr>
            <th>Last Name</th>
            <td>{{user.last_name}}</td>
        </tr>
        <tr>
            <th>Email Id</th>
            <td>{{user.email}}</td>
        </tr>
            <th>Patient ID</th>
            <td>{{user.patientprofile.id_code}}</td>
        </tr>
    </tbody>
    </table>
      <div class="text-right">
        <a class="btn btn-warning" href="{%  url 'patient:edit' user.id %}">Edit</a>
        <a class="btn btn-danger" href="{%  url 'patient:delete' user.id %}">Delete</a>
    </div>
{% endblock content %}

templates/patient/edit.html
{% extends 'base.html' %}


{% block content %}
<br>
    <form method="POST">
        {% csrf_token %}
        <table class="table table-bordered table-light">
            {{user_form.as_table}}
        </table>
        <br>
        <button type="submit" class="btn btn-warning float-right">Update Patient</button>
    </form>
{% endblock content %}

templates/patient/index.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
    <div class="col-sm-8">
         <p>
            <div class="float-left"><h3>List of {{title}}</h3></div>
            {% if request.ad == 'Admin' %}
            <a class="btn btn-success float-right" href="{%  url 'patient:add' %}">Add employee</a>
            {% endif %}
        </p>
        <div class="table-responsive-sm">
        {% if users %}
            <table class="table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th>Name</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <th scope="row">
                            {{user.first_name}} {{user.last_name}}
                            <span class="badge badge-default">{{user.email}}</span>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-primary" href="{%  url 'patient:details' user.id %}">Details</a>
                            <a class="btn btn-primary" href="{%  url 'patient:edit' user.id %}">Edit</a>
                            <a class="btn btn-primary" href="{%  url 'patient:delete' user.id %}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
        {% else %}
            <p>There is no patient available.</p>
        {% endif %}
        </div>
    </div>
    <div class="col-sm-4">
        <p><h3>Recent Surveys</h3></p>
        {% if questions %}
            <table class="table table-bordered">
                <thead class="thead-light">
                <tr>
                    <th>Survey</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for question in questions %}
                    <tr>
                        <th scope="row">
                            <a class="" href="{% url 'question_content' question.id %}">{{ question.title }}</a>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-primary" href="{% url 'survey_details' question.id %}">Details</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>There is no question available.</p>
        {% endif %}
    </div>
</div>
{% endblock content %}