KAP/urls.py
from django.contrib import admin
from django.urls import path, include
from patient.views import user_login, user_logout, success
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include(('patient.urls','patient'),namespace='patient')),
    path('survey/', include(('survey.urls','survey'),namespace='survey')),
    path('appointments/',include(('appointments.urls','appointments'),namespace='appointments')),    

    path('login/', user_login, name="user_login"),
    path('success/', success, name="user_success"),
    path('logout/', user_logout, name="user_logout"),
]

appointments/urls.py
from django.urls import path
from django.contrib import admin

from . import views

urlpatterns = [
    path('', views.appointment_list, name='list'),
    path('create/', views.appointment_create, name='create'),
    path('detail/<int:id>/', views.appointment_detail, name='detail'),
    path('list/', views.appointment_list, name='list'),
    path('edit/<int:id>/', views.appointment_edit, name='edit'),
    path('delete/<int:id>/', views.appointment_delete, name='delete'),
]

appointments/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

User = settings.AUTH_USER_MODEL
# Create your models here.

class Appointment(models.Model):
	user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)	
	title = models.CharField(max_length=50)
	date = models.DateTimeField('Termin')
	comment = models.CharField(max_length=200)
	files = models.PositiveIntegerField(default=0)
	timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("appointments:detail",kwargs={"id": self.id})
        #return "/appointments/detail/%s" %(self.id)

appointments/forms.py
from django import forms
from .models import Appointment

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = [
            "title",
            "date",
            "comment",
        ]
    first_name = forms.DateTimeInput()# TextInput(attrs={'id': 'firstname',  'class':'form-control'})
    """
    title = forms.CharField(label='Titel', max_length=50)
    date = forms.DateTimeInput()
    comment = forms.CharField(label='Kommentar',max_length=200)
    
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)	
    title = models.CharField(max_length=50)
    date = models.DateTimeField('Termin')
    comment = models.CharField(max_length=200)
    files = models.PositiveIntegerField(default=0)
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)
    """

appointments/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
# Create your views here.
from .models import Appointment
from .forms import AppointmentForm

def removeSensitiveAppointment(request, appointment):
    print(request.user)
    print(appointment.user)
    if request.user != appointment.user:
            appointment.user = None
            appointment.title = None
            appointment.comment = None
            appointment.files = 0
            appointment.timestamp = None
            appointment.id = 0

def removeSensitiveData(request,queryset):
    for appointment in queryset:
        removeSensitiveAppointment(request, appointment)

@login_required(login_url="/login/")
def appointment_create(request):
    if request.user.is_authenticated:
        form = AppointmentForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('/appointments')
        
        context = {
        "form": form,
        }
        return render(request,"appointments/add.html",context)
    else:
        return HttpResponse("<h1>Bitte loggen sie sich zuerst ein</h1>")

@login_required(login_url="/login/")
def appointment_detail(request,id=None):
    instance = get_object_or_404(Appointment,id=id)
    if request.user != instance.user:
        return HttpResponse('<h1>Unauthorized</h1>', status=401)
    context = {
        "content": str(instance.title)
    }
    return render(request,"appointments/details.html",context)

@login_required(login_url="/login/")
def appointment_list(request):
    queryset = Appointment.objects.all()
    removeSensitiveData(request,queryset)
    context = {
        "title":"Appointments",
        "appointments": queryset,
    }
    return render(request,"appointments/index.html",context)

@login_required(login_url="/login/")
def appointment_edit(request, id=None):
    instance = get_object_or_404(Appointment,id=id)
    if request.user != instance.user:
        return HttpResponse('<h1>Unauthorized</h1>', status=401)
    context = {
        "content": str(instance.title)
    }
    return render(request,"appointments/details.html",context)

@login_required(login_url="/login/")
def appointment_delete(request, id=None):
    instance = get_object_or_404(Appointment,id=id)
    if request.user != instance.user:
        return HttpResponse('<h1>Unauthorized</h1>', status=401)
    return HttpResponse("<h1>Delete</h1>")

templates/appointments/add.html
{% extends 'base.html' %}


{% block content %}


<p>
        <div class="float-left">
                <h3>Neuen Termin erstellen</h3>
        </div>       
</p>
<br><br>
<p>
    <div>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Abschicken</button>
        </form>
    </div>
</p>
{% endblock content %}

templates/appointments/details.html
{% extends 'base.html' %}


{% block content %}
        <h1> {{ content }} </h1>
{% endblock content %}

templates/appointments/index.html
{% extends 'base.html' %}

{% block content %}
<div>
        <p>
                <div class="float-left">
                        <h3>List of {{title}}</h3>
                </div>
                <button type="submit"  onclick="location.href = '/appointments/create';" class="btn btn-success float-right">Neuer Termin</button>
               
        </p>
        {% if appointments %}
            <table class="table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th>Appointment</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for appointment in appointments %}
                    <tr>
                        <th scope="row">
                            {{appointment.date}}
                        </th>
                        <td class="text-center">
                            {% if appointment.title != None %}
                            <a class="btn btn-primary" href="{%  url 'appointments:detail' appointment.id %}">Details</a>
                            <a class="btn btn-primary" href="{%  url 'appointments:edit' appointment.id %}">Edit</a>
                            <a class="btn btn-primary" href="{%  url 'appointments:delete' appointment.id %}">Delete</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
        {% else %}
            <br><br><p>There are no current Appointments.</p>
        {% endif %}


</div>
{% endblock content %}