KAP/urls.py
from django.contrib import admin
from django.urls import path, include
from patient.views import user_login, user_logout, success
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include(('patient.urls','patient'),namespace='patient')),
    path('survey/', include(('survey.urls','survey'),namespace='survey')),
    path('appointments/',include(('appointments.urls','appointments'),namespace='appointments')),    

    path('login/', user_login, name="user_login"),
    path('success/', success, name="user_success"),
    path('logout/', user_logout, name="user_logout"),
]

patient/urls.py
from django.urls import path
from patient.views import *

urlpatterns = [
    path('', patient_list, name='list'),
    path('<int:id>/details/', patient_details, name="details"),
    path('<int:id>/edit/', patient_edit, name="edit"),
    path('add/', patient_add, name="add"),
    path('<int:id>/delete/', patient_delete, name="delete"),
    ]

survey/urls.py
from django.urls import path
from survey.views import *

urlpatterns = [
    path('', index, name='survey_list'),
    path('<int:id>/details', details, name='survey_details'),
    path('<int:id>/', question_content, name='question_content'),
    ]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>KAP Termine</title>
         <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    </head>
    <body>
        {% if request.user.is_authenticated  %}
            {% include 'header.html'  %}
        {% endif %}
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/header.html
<div class="navbar navbar-expand-lg navbar-light bg-light">
    <span class="navbar-brand mb-0 h1">Termin Management </span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'appointments:list' %}">
                    {{ "appointments" | capfirst }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'patient:list' %}">
                    {{ "patient" | capfirst }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'survey:survey_list' %}">
                    {{ "Survey" | capfirst }}
                    <span class="badge badge-primary badge-pill ">{{ survey_count }}</span>
                </a>
            </li>
        </ul>
    </div>
    {% if user %}
        <div class="test-right">
            <form method="POST" action="/logout/">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Logout">
            </form>
        </div>
    {% endif %}
</div>